version: 0.2

phases:
  install:
    commands:
      - echo "Installing Packer"
      - curl -o packer.zip $PACKER_ZIP_URL && unzip packer.zip

  pre_build:
    commands:
      - cp -a $PACKER_PROJECT_DIR/$PACKER_PROJECT_NAME/* .
      - ls -la
      - echo "Validating Packer template $TEMPLATE"
      - ./packer validate $PACKER_TEMPLATE_NAME 
  build:
    commands:
      - ./packer build -color=false $PACKER_TEMPLATE_NAME | tee build.log

  post_build:
    commands:
      - egrep "${AWS_REGION}\:\sami\-" build.log | cut -d' ' -f2 > ami_id.txt
      # Packer doesn't return non-zero status; we must do that if Packer build failed
      - test -s ami_id.txt || exit 1
      - sed -i.bak "s/<<AMI-ID>>/$(cat ami_id.txt)/g" codebuild/ami_builder_event.json
      - aws events put-events --entries file://codebuild/ami_builder_event.json
      - echo "build completed on `date`"

artifacts:
  files:
    - codebuild/ami_builder_event.json
    - build.log
    - ami_id.txt
  discard-paths: yes
