#!/bin/sh +x
PATH=$PATH:/usr/bin:/bin

#Create base linux Aplication directories
mkdir -p /apps /data /logs

# Install UCOP custom Repo
cat << EOF > /etc/yum.repos.d/custom_RHEL6-system.repo
[custom_RHEL6-system]
name=UCOP Custom RHEL6-system
baseurl=http://unxsmtp01.ucop.edu/repo/UCOP/RHEL6-system
gpgcheck=0
gpgkey=http://unxsmtp01.ucop.edu/repo/keys/ucop-smt-pubgpg.key,http://unxsmtp01.ucop.edu/repo/keys/RPM-GPG-KEY-puppetlabs
cost=500
EOF

yum-config-manager --enable custom_RHEL6-system

# Install 3rd-party packages
yum install -y CentrifyDC
yum install -y AvamarClient

#Install SSM
yum install -y https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/linux_amd64/amazon-ssm-agent.rpm
systemctl enable amazon-ssm-agent
systemctl start amazon-ssm-agent

#Allow passwd login
sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config

